articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
		path('', views.index, name ='index'),
		path('<int:article_id>/', views.detail, name ='detail'),
		path('<int:article_id>/leave_comment/', views.leave_comment, name ='leave_comment'),
		path('post/new/', views.post_new, name='post_new'),
		path('<int:article_id>/edit/', views.post_edit, name='post_edit'),
	]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]

articles/models.py
from django.db import models
import datetime
from django.utils import timezone

class Article(models.Model):
    article_title = models.CharField('название статьи', max_length=200)
    author_name = models.CharField('имя автора', max_length=50, default='anon')
    article_text = models.TextField('текст статьи')
    pub_date = models.DateTimeField('дата публикации', default = timezone.now())


    def __str__(self):
        return self.article_title


    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))


    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('имя автора', max_length=50, default = 'anon')
    comment_text = models.CharField('текст комментария', max_length=200)
    pub_date = models.DateTimeField('дата публикации', default=timezone.now())

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

articles/forms.py
from django import forms

from .models import Article

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ('article_title', 'article_text',)

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Article
from .forms import ArticleForm
from django.utils import timezone

def index(request):
	latest_articles_list = Article.objects.order_by('-pub_date')[:5]
	return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})

def detail(request, article_id):
	try:
		a = Article.objects.get( id =  article_id )
	except:
		raise Http404('Статья не найдена')
	latest_comments_list = a.comment_set.order_by('-id')[:10]
	return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list})

def leave_comment(request, article_id):
	try:
		a = Article.objects.get( id =  article_id)
	except:
		raise Http404('Статья не найдена')
	a.comment_set.create(author_name = request.POST['name'], comment_text = request.POST['text'])
	return HttpResponseRedirect(reverse('articles:detail', args  = (a.id, )))

def post_new(request):
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('detail', article_id=post.id)
    else:
        form = ArticleForm()
    return render(request, 'articles/post_edit.html', {'form': form})

def post_edit(request, article_id):
    post = get_object_or_404(Article, id=article_id)
    if request.method == "POST":
        form = ArticleForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('articles:detail', article_id=post.id)
    else:
        form = ArticleForm(instance=post)
    return render(request, 'articles/post_edit.html', {'form': form})

articles/templates/articles/base.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/articles.css' %}">
        <title>Мой сайт. {% block title %}{% endblock %}</title>
    </head>

    <body>
    <div class="page-header">
        <a href="{% url 'articles:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        <h1><a href="/articles">Статьи ни о чем</a></h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-15">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
    </body>
</html>

articles/templates/articles/detail.html
{% extends 'articles/base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}
 <div class="title">
     <h1>{{article.article_title}}</h1>
     {% if user.is_authenticated %}
        <a href="{% url 'articles:post_edit' article.id %}" ><span class="glyphicon glyphicon-plus"></span></a>
     {% endif %}
    {% if article.was_published_recently %}
    <em>  СВЕЖАЯ СТАТЬЯ!</em>
     {% endif %}
 </div>
    <div class="post">
        <p>{{article.article_text|linebreaksbr}}</p>
        <div class = 'data'>
             <em>{{article.pub_date}}</em>
        </div>

    <hr>
    <p><h2>Комментарии:</h2></p>
    {% if latest_comments_list %}
        {% for c in latest_comments_list %}
                <strong>{{c.author_name}}: </strong>
                <br />{{c.comment_text}}
                <div class="datacom">
                    <em>{{c.pub_date}}</em>
                </div>
            </p>
        {% endfor %}
    {% else %}
    <em>Комментарии не найдены</em>
    {% endif %}
    <hr>

    <form action="{% url 'articles:leave_comment' article.id %}" method="post" class="post-form">
        {% csrf_token %}
        <input type="text" required placeholder="Ваше имя" name="name"><br>
        <textarea name="text" required="" placeholder="Тект комментария" cols="30" rows="10"></textarea><br>
        <button type="submit">Оставить комментарий</button>
    </form>

</div>
{% endblock %}

articles/templates/articles/list.html
{% extends 'articles/base.html' %}

{% block title %}
Последние статьи
{% endblock %}

{% block content %}
    {% if latest_articles_list %}
            {% for a in latest_articles_list %}
                <div class="post">
                    {% if user.is_authenticated %}
                        <h2><a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a></h2>
                    {% endif %}
                        <div class = 'datecom'>
                            <p>Опубликовано: {{a.pub_date}}</p>
                        </div>
                </div>
            {% endfor %}
    {% else %}
            Статьи не найдены =(
    {% endif %}
{% endblock %}

articles/templates/articles/list0.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/articles.css' %}">
        <title>Последние статьи blog</title>
    </head>

    <body>
        <div class="page-header">
            <h1>Последние статьи</h1>
        </div>

        <div class="content container">
                    {% if latest_articles_list %}
                        {% for a in latest_articles_list %}
                            <div class="post">
                                <h2><a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a></h2>
                                <div class = 'date'>
                                    <p>Опубликовано: {{a.pub_date}}</p>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        Статьи не найдены =(
                    {% endif %}
        </div>
    </body>
</html>

articles/templates/articles/post_edit.html
{% extends 'articles/base.html' %}

{% block title %}
Создание статьи
{% endblock %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

mysite/templates/articles/detail.html
{% extends 'articles/base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}
<a href="/articles"> Назад к списку статей </a>
<h1>{{article.article_title}}</h1>
{% if article.was_published_recently %}
<em>СВЕЖАЯ СТАТЬЯ!</em>

<p>{{article.article_text}}</p>
{% endif %}
<em>{{article.pub_date}}</em>


<hr>
{% if latest_comments_list %}
    {% for c in latest_comments_list %}
        <p>
            <strong>{{c.author_name}}</strong>
            {{c.comment_text}}
            <br /><em>{{c.pub_date}}</em>
        </p>
    {% endfor %}
{% else %}
Комментарии не найдены
{% endif %}
<hr>

<form action="{% url 'articles:leave_comment' article.id %}" method="post">
    {% csrf_token %}
    <input type="text" required placeholder="Ваше имя" name="name"><br>
    <textarea name="text" required="" placeholder="Тект комментария" cols="30" rows="10"></textarea><br>
    <button type="submit">Оставить комментарий</button>
</form>

{% endblock %}

mysite/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}
Последние статьи
{% endblock %}

{% block content %}
    <h1>Последние статьи</h1>
    {% if latest_articles_list %}
        {% for a in latest_articles_list %}
            <div>
                <h2><a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a></h2>
                <p>Опубликовано: {{a.pub_date}}</p>
            </div>
        {% endfor %}
    {% else %}
        Статьи не найдены =(
    {% endif %}
{% endblock %}

mysite/templates/base.html
{% load static %}
<html lang="ru">
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="static 'base.css'">
    <meta charset="UTF-8"/>
    <title>Мой сайт. {% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>